services:
  db:
    image: mysql:8.0.37
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
  rails:
    build:
      context: ./back_end
    command: bash -c "tail -f log/development.log"
    volumes:
      - ./back_end:/back_end
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  next:
    build:
      dockerfile: ./front_end/Dockerfile
    volumes:
      - ./front_end:/front_end
    ports:
      - "8000:3000"
    tty: true
    stdin_open: true
volumes:
  mysql_data:
