FROM --platform=linux/x86_64 nginx:latest

# ヘルスチェック用
RUN apt-get update && apt-get install -y curl vim sudo lsof

# インクルード用のディレクトリ内を削除する
RUN rm -f /etc/nginx/conf.d/*

# Nginxの設定ファイルをコンテナにコピーする
ADD nginx.conf /etc/nginx/myapp.conf

# ビルド完了後にNginxを起動する
CMD /usr/sbin/nginx -g 'daemon off;' -c /etc/nginx/myapp.conf

EXPOSE 80
