inherit_from: .rubocop_todo.yml

require:
  # - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/*'
    - 'config/initializers/**/*'
    - 'db/**/*'
    - 'lib/tasks/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'spec/**/*'
    - 'storage/**/*'
    - 'terraform/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  NewCops: enable
  TargetRubyVersion: 3.2

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/**/*'

Metrics/MethodLength:
  Max: 20

# コメントにASCII文字以外の使用を許容するためfalseを設定する
Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# trueかfalseを設定しないと警告を出力するためtrueを設定する
Style/HashEachMethods:
  Enabled: true

# trueかfalseを設定しないと警告を出力するためtrueを設定する
Style/HashTransformKeys:
  Enabled: true

# trueかfalseを設定しないと警告を出力するためtrueを設定する
Style/HashTransformValues:
  Enabled: true

Style/NumericPredicate:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/RedundantConstantBase:
  Exclude:
    - 'config/environments/production.rb'
