source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.3"

# railsの起動時間を短縮するためbootsnapを導入する（標準gem）
gem "bootsnap", require: false

gem "mysql2", "0.5.6"

gem "puma", "5.6.8"

gem "rails", "7.0.8.4"

# タイムゾーン情報を提供する（標準gem）
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"

  gem 'rspec-rails'

  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end
