source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.3"
gem "rails", "7.0.8.4"

# メッセージを日本語化する
gem "rails-i18n"

# railsの起動時間を短縮するためbootsnapを導入する（標準gem）
gem "bootsnap", require: false

gem "mysql2", "0.5.6"

gem "puma", "5.6.8"

# cors設定を管理する
gem "rack-cors"

# 環境毎のフロントエンド・バックエンドの疎通ポート番号を管理する
gem "config"

# タイムゾーン情報を提供する（標準gem）
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

# ユーザー認証を提供する
gem "devise"

# deviseを日本語化する
gem "devise-i18n"

# ユーザーのトークン認証を提供する
gem "devise_token_auth"

# ページネーション機能を提供する
gem "kaminari"

# enum を日本語化する
gem "enum_help"

# レスポンスJSONを制御する
gem "active_model_serializers"

group :development, :test do
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"

  gem "rspec-rails"

  # テストデータを生成する
  gem "factory_bot_rails"
  gem "faker"

  # 開発環境でメール送信をテストする
  gem "letter_opener_web"

  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"

  # N+1発生時にアラートを表示する
  gem "bullet"
end
